chromedefault:
	xdg-settings set default-web-browser google-chrome.desktop

firefoxdefault:
	xdg-settings set default-web-browser firefox.desktop

edgedefault:
	xdg-settings set default-web-browser microsoft-edge-beta.desktop

openindex:
	xdg-open index.html